spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springbootproject
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver

      druid:
        aop-patterns: com.atguigu.demo.*
        filters: stat,wall

        stat-view-servlet:
          enabled: true
          login-password: admin
          login-username: admin
          reset-enable: false

        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.png,*.css,*.ico,/druid/*'

        filter:
          stat:
            slow-sql-millis: 1000
            log-slow-sql: true
            enabled: true

          wall:
            enabled: true
            config:
              drop-table-allow: false
mybatis:
  config-location: classpath:mybaties/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml